# Generated by Django 5.0.7 on 2024-08-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscriptions_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
