# Generated by Django 5.0.7 on 2024-08-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_usersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='Subscriptions',
            new_name='subscription',
        ),
    ]
