# Generated by Django 5.0.7 on 2024-08-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_rename_subscriptions_usersubscription_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
